var games = require('./games')
var strategies = require('./strategies')
var tournament = require('./tournament')
var rules = require('./rules')
var players = require('./players')
window.Player = players.Player;
window.Learner = rules.Learner;
window.RandomLearner = rules.RandomLearner;
window.OverallLearner = rules.OverallLearner;
window.NeighborhoodLearner = rules.NeighborhoodLearner;
window.RandomMatcher = rules.RandomMatcher;
window.Matcher = rules.Matcher;
window.Tournament = tournament.Tournament;
window.Strategy = strategies.Strategy;
window.TitForTat = strategies.TitForTat;
window.AllDefect = strategies.AllDefect;
window.Game = games.Game;
window.PrisonersDilemma = games.PrisonersDilemma;
window.PrisonersDilemmaMoves = games.PrisonersDilemmaMoves;
window.PrisonersDilemmaPayouts = games.PrisonersDilemmaPayouts;
